[package]
name = "tarc"
version = "0.1.0"
edition = "2018"
authors = ["Aurimas Blažulionis <0x60@pm.me>"]
license = "MIT"
repository = "https://github.com/h33p/tarc"
description = "Transposable, type-erasable, and FFI-safe Arc"
readme = "README.md"

[lib]
bench = false

